import Histogram = require("./utils/probes/Histogram.js");
import Meter = require("./utils/probes/Meter.js");
import Counter = require("./utils/probes/Counter.js");
export const _started: boolean;
export const _var: {};
export const AVAILABLE_AGG_TYPES: string[];
export const AVAILABLE_MEASUREMENTS: string[];
export const default_aggregation: string;
export const default_type: string;
