export = Histogram;
declare function Histogram(opts: any): void;
declare class Histogram {
    constructor(opts: any);
    _measurement: any;
    _call_fn: any;
    _sample: EDS;
    _min: any;
    _max: any;
    _count: number;
    _sum: number;
    _varianceM: number;
    _varianceS: number;
    _ema: number;
    update(value: any): void;
    percentiles(percentiles: any): {};
    reset(): void;
    val(): any;
    getMin(): any;
    getMax(): any;
    getSum(): number;
    getCount(): number;
    getEma(): number;
    fullResults(): {
        min: any;
        max: any;
        sum: number;
        variance: number;
        mean: number;
        stddev: number;
        count: number;
        median: any;
        p75: any;
        p95: any;
        p99: any;
        p999: any;
        ema: number;
    };
    _updateMin(value: any): void;
    _updateMax(value: any): void;
    _updateVariance(value: any): any;
    _updateEma(value: any): number;
    _calculateMean(): number;
    _calculateVariance(): number;
    _calculateStddev(): number;
}
import EDS = require("../EDS.js");
